root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main cmd/api/main.go"
  bin = "./tmp/main"
  include_ext = ["go", "tpl", "tmpl", "html", "env"]
  exclude_dir = ["assets", "tmp", "vendor", "tests", "bin", "migrations"]
  exclude_regex = ["_test.go"]
  delay = 1000
  stop_on_error = true
  kill_delay = "500ms"

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[log]
  time = true

[misc]
  clean_on_exit = true
